<html>
<script src="JQuery/jquery-1.9.1.js"></script><script src="JQuery/jquery-ui.js"></script>
<link href="table_sorter/css/theme.default.css" rel="stylesheet">
<script type="text/javascript" src="table_sorter/js/jquery.tablesorter.min.js"></script><script type="text/javascript" src="table_sorter/js/jquery.tablesorter.widgets.min.js"></script><script type="text/javascript">
$(function() {
	$( "#tabs" ).tabs();
	$('table').tablesorter({
			sortList: [[0,0]],
			widgets        : ['zebra', 'columns'],
			usNumberFormat : true,
			sortRestart    : true
	});
});
</script>
<body>
<table style="empty-cells:show;" id="veiwStandingTable" class="tablesorter" border="1px">
<thead>
<tr>
<th>Rank</th><th>Team Name</th><th>Solved</th><th>Time</th><th>A: Service with a Smile</th><th>B: Omelette du Fromage</th><th>C: Stacks of Pancakes</th><th>D: Regular Customers</th><th>E: Break-faster Delivery</th><th>F: An Efficient Kitchen</th><th>G: Waffle Coverage</th><th>H: Clumsy</th><th>I: Breakfast Stations</th><th>J: A "Complete" Breakfast</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td><td>TJ High School: SENIOR TEAM</td><td>8</td><td>863</td><td style="text-align:center;background:#58FA58;border-color:white;">5/80</td><td style="text-align:center;background:#58FA58;border-color:white;">1/70</td><td style="text-align:center;background:#58FA58;border-color:white;">2/8</td><td style="text-align:center;background:#58FA58;border-color:white;">1/29</td><td style="text-align:center;background:#58FA58;border-color:white;">4/160</td><td style="text-align:center;background:#58FA58;border-color:white;">1/146</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/88</td><td style="text-align:center;background:#58FA58;border-color:white;">3/82</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>2</td><td>Deep Run HS: HTCPCP://</td><td>5</td><td>533</td><td style="text-align:center;background:#58FA58;border-color:white;">4/144</td><td style="text-align:center;background:#58FA58;border-color:white;">1/74</td><td style="text-align:center;background:#58FA58;border-color:white;">2/8</td><td style="text-align:center;background:#58FA58;border-color:white;">1/36</td><td style="text-align:center;background:#FF6666; border-color:white;">4/--</td><td style="text-align:center;background:#58FA58;border-color:white;">3/151</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">7/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>3</td><td>South Lakes HS: SLHS Team 1</td><td>5</td><td>548</td><td style="text-align:center;background:#58FA58;border-color:white;">1/24</td><td style="text-align:center;background:#58FA58;border-color:white;">3/117</td><td style="text-align:center;background:#58FA58;border-color:white;">1/14</td><td style="text-align:center;background:#58FA58;border-color:white;">1/42</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">6/211</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">7/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>4</td><td>TJ High School: INTERMEDIATE TEAM</td><td>5</td><td>597</td><td style="text-align:center;background:#58FA58;border-color:white;">1/60</td><td style="text-align:center;background:#58FA58;border-color:white;">4/233</td><td style="text-align:center;background:#58FA58;border-color:white;">1/32</td><td style="text-align:center;background:#58FA58;border-color:white;">1/80</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/132</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>5</td><td>TJ High School: JUNIOR TEAM</td><td>5</td><td>655</td><td style="text-align:center;background:#58FA58;border-color:white;">1/37</td><td style="text-align:center;background:#58FA58;border-color:white;">1/139</td><td style="text-align:center;background:#58FA58;border-color:white;">1/73</td><td style="text-align:center;background:#58FA58;border-color:white;">2/157</td><td style="text-align:center;background:#58FA58;border-color:white;">1/229</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>6</td><td>Deep Run HS: Fantastic 100</td><td>4</td><td>150</td><td style="text-align:center;background:#58FA58;border-color:white;">1/36</td><td style="text-align:center;background:#58FA58;border-color:white;">1/27</td><td style="text-align:center;background:#58FA58;border-color:white;">1/31</td><td style="text-align:center;background:#58FA58;border-color:white;">1/56</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">5/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>7</td><td>Dominion HS: The Bradleys</td><td>4</td><td>207</td><td style="text-align:center;background:#58FA58;border-color:white;">2/48</td><td style="text-align:center;background:#58FA58;border-color:white;">1/37</td><td style="text-align:center;background:#58FA58;border-color:white;">1/42</td><td style="text-align:center;background:#58FA58;border-color:white;">1/60</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>8</td><td>Albemarle HS: pizza_slice.py.java</td><td>4</td><td>444</td><td style="text-align:center;background:#58FA58;border-color:white;">3/44</td><td style="text-align:center;background:#58FA58;border-color:white;">3/143</td><td style="text-align:center;background:#58FA58;border-color:white;">1/75</td><td style="text-align:center;background:#58FA58;border-color:white;">2/82</td><td style="text-align:center;background:#FF6666; border-color:white;">4/--</td><td style="text-align:center;background:#FF6666; border-color:white;">4/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>9</td><td>Battlefield HS: Betaware 1</td><td>4</td><td>501</td><td style="text-align:center;background:#58FA58;border-color:white;">3/69</td><td style="text-align:center;background:#58FA58;border-color:white;">3/152</td><td style="text-align:center;background:#58FA58;border-color:white;">2/104</td><td style="text-align:center;background:#58FA58;border-color:white;">1/76</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">6/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>10</td><td>Forest Park HS: Forest Park Java Bruins T</td><td>4</td><td>590</td><td style="text-align:center;background:#58FA58;border-color:white;">2/163</td><td style="text-align:center;background:#58FA58;border-color:white;">1/76</td><td style="text-align:center;background:#58FA58;border-color:white;">1/210</td><td style="text-align:center;background:#58FA58;border-color:white;">1/121</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>11</td><td>Fairfax HS: Wired Up</td><td>4</td><td>602</td><td style="text-align:center;background:#58FA58;border-color:white;">3/168</td><td style="text-align:center;background:#58FA58;border-color:white;">4/176</td><td style="text-align:center;background:#58FA58;border-color:white;">1/36</td><td style="text-align:center;background:#58FA58;border-color:white;">2/102</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>12</td><td>Freedom HS: Does_Not_Compute</td><td>4</td><td>607</td><td style="text-align:center;background:#58FA58;border-color:white;">2/164</td><td style="text-align:center;background:#58FA58;border-color:white;">2/141</td><td style="text-align:center;background:#58FA58;border-color:white;">1/38</td><td style="text-align:center;background:#58FA58;border-color:white;">1/224</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>13</td><td>Battlefield HS: Betaware 3</td><td>3</td><td>249</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/40</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/89</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/120</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>14</td><td>South Lakes HS: SLHS Team 2</td><td>3</td><td>364</td><td style="text-align:center;background:#58FA58;border-color:white;">2/84</td><td style="text-align:center;background:#58FA58;border-color:white;">3/127</td><td style="text-align:center;background:#58FA58;border-color:white;">1/93</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>15</td><td>Forest Park HS: Forest Park Java Bruins T</td><td>3</td><td>475</td><td style="text-align:center;background:#58FA58;border-color:white;">5/221</td><td style="text-align:center;background:#58FA58;border-color:white;">3/62</td><td style="text-align:center;background:#58FA58;border-color:white;">1/72</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>16</td><td>Stone Bridge HS: Tell them about the twink</td><td>3</td><td>545</td><td style="text-align:center;background:#58FA58;border-color:white;">6/228</td><td style="text-align:center;background:#58FA58;border-color:white;">3/98</td><td style="text-align:center;background:#58FA58;border-color:white;">1/79</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>17</td><td>Stone Bridge HS: I'm Batman</td><td>3</td><td>607</td><td style="text-align:center;background:#58FA58;border-color:white;">6/231</td><td style="text-align:center;background:#58FA58;border-color:white;">3/217</td><td style="text-align:center;background:#58FA58;border-color:white;">1/39</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>18</td><td>Loudoun Valley HS: LVHS Team #2</td><td>3</td><td>696</td><td style="text-align:center;background:#58FA58;border-color:white;">8/224</td><td style="text-align:center;background:#58FA58;border-color:white;">1/86</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">3/206</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td>
</tr>
<tr>
<td>19</td><td>Rock Ridge: Phoenix Song</td><td>2</td><td>180</td><td style="text-align:center;background:#58FA58;border-color:white;">1/98</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/82</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>20</td><td>Lake Braddock SS: LB #1</td><td>2</td><td>219</td><td style="text-align:center;background:#FF6666; border-color:white;">5/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/172</td><td style="text-align:center;background:#58FA58;border-color:white;">1/47</td><td style="text-align:center;background:#FF6666; border-color:white;">7/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>21</td><td>NCSSM: NCSSM 1</td><td>2</td><td>262</td><td style="text-align:center;background:#58FA58;border-color:white;">3/174</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/48</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">4/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>22</td><td>Deep Run HS: '; DROP TABLE teams --</td><td>2</td><td>314</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/226</td><td style="text-align:center;background:#58FA58;border-color:white;">1/68</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>23</td><td>Rock Ridge: !(last)</td><td>2</td><td>321</td><td style="text-align:center;background:#58FA58;border-color:white;">4/188</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/73</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>24</td><td>Battlefield HS: Betaware 2</td><td>2</td><td>372</td><td style="text-align:center;background:#FF6666; border-color:white;">5/--</td><td style="text-align:center;background:#FF6666; border-color:white;">4/--</td><td style="text-align:center;background:#58FA58;border-color:white;">3/216</td><td style="text-align:center;background:#58FA58;border-color:white;">1/116</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>25</td><td>Potomac Falls HS: Useless Variables</td><td>2</td><td>436</td><td style="text-align:center;background:#58FA58;border-color:white;">3/224</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/172</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>26</td><td>GSST: Governor's School for Sci</td><td>1</td><td>11</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/11</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>27</td><td>Albemarle HS: Javalanche</td><td>1</td><td>15</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/15</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>28</td><td>Loudoun Valley HS: LVHS Team #1</td><td>1</td><td>33</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/33</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#FF6666; border-color:white;">4/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td>
</tr>
<tr>
<td>29</td><td>Freedom HS: Freedom Team 2</td><td>1</td><td>44</td><td style="text-align:center;background:#FF6666; border-color:white;">5/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/44</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>30</td><td>Broad Run High School: BRHS Z Team</td><td>1</td><td>46</td><td style="text-align:center;background:#58FA58;border-color:white;">1/46</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>31</td><td>Lake Braddock SS: LB #2</td><td>1</td><td>81</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/81</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>32</td><td>Stone Bridge HS: I'm Your Density</td><td>1</td><td>82</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/82</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>33</td><td>Powhatan HS: Adobe-Wan Kenobi and the </td><td>1</td><td>91</td><td style="text-align:center;background:#FF6666; border-color:white;">7/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/91</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>34</td><td>Dominion HS: DHS3</td><td>1</td><td>107</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/107</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>35</td><td>Rock Ridge: The Firewall</td><td>1</td><td>166</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/166</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>36</td><td>Galileo HS: Execution</td><td>1</td><td>205</td><td style="text-align:center;background:#58FA58;border-color:white;">2/185</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>37</td><td>Dominion HS: DHS2</td><td>1</td><td>217</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/217</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>38</td><td>Lake Braddock SS: LB #3</td><td>1</td><td>221</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/221</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>39</td><td>South Lakes HS: SLHS Team 3</td><td>1</td><td>230</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/230</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>40</td><td>Loudoun Valley HS: LVHS Team #3</td><td>0</td><td>0</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>40</td><td>Potomac Falls HS: :-)</td><td>0</td><td>0</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>40</td><td>Potomac Falls HS: Spaghetti Coders United</td><td>0</td><td>0</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>40</td><td>Powhatan HS: IndexOutOfHounds</td><td>0</td><td>0</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>40</td><td>Powhatan HS: The Cool Operators</td><td>0</td><td>0</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
</tbody>
</table>
</body>
</html>
