<html>
<script src="JQuery/jquery-1.9.1.js"></script><script src="JQuery/jquery-ui.js"></script>
<link href="table_sorter/css/theme.default.css" rel="stylesheet">
<script type="text/javascript" src="table_sorter/js/jquery.tablesorter.min.js"></script><script type="text/javascript" src="table_sorter/js/jquery.tablesorter.widgets.min.js"></script><script type="text/javascript">
$(function() {
	$( "#tabs" ).tabs();
	$('table').tablesorter({
			sortList: [[0,0]],
			widgets        : ['zebra', 'columns'],
			usNumberFormat : true,
			sortRestart    : true
	});
});
</script>
<body>
<table style="empty-cells:show;" id="veiwStandingTable" class="tablesorter" border="1px">
<thead>
<tr>
<th>Rank</th><th>Team Name</th><th>Solved</th><th>Time</th><th>A: Mario Polo</th><th>B: Coins</th><th>C: Kirby Your Enthusiasm</th><th>D: Sortle!</th><th>E: Power-up Probability</th><th>F: Jmp Mario</th><th>G: donKEY Kong</th><th>H: High Scores!</th><th>I: Collatz Chain Chomp</th><th>J: Samus Charge</th><th>K: Pokeballs</th><th>L: Toad Puzzle</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td><td>TJ High School: TJHSST Senior Team</td><td>12</td><td>650</td><td style="text-align:center;background:#58FA58;border-color:white;">1/2</td><td style="text-align:center;background:#58FA58;border-color:white;">1/4</td><td style="text-align:center;background:#58FA58;border-color:white;">1/14</td><td style="text-align:center;background:#58FA58;border-color:white;">1/18</td><td style="text-align:center;background:#58FA58;border-color:white;">1/22</td><td style="text-align:center;background:#58FA58;border-color:white;">1/59</td><td style="text-align:center;background:#58FA58;border-color:white;">1/34</td><td style="text-align:center;background:#58FA58;border-color:white;">1/45</td><td style="text-align:center;background:#58FA58;border-color:white;">1/38</td><td style="text-align:center;background:#58FA58;border-color:white;">2/177</td><td style="text-align:center;background:#58FA58;border-color:white;">1/74</td><td style="text-align:center;background:#58FA58;border-color:white;">1/143</td>
</tr>
<tr>
<td>2</td><td>RMHS: RMHS 1</td><td>12</td><td>927</td><td style="text-align:center;background:#58FA58;border-color:white;">1/1</td><td style="text-align:center;background:#58FA58;border-color:white;">1/3</td><td style="text-align:center;background:#58FA58;border-color:white;">1/8</td><td style="text-align:center;background:#58FA58;border-color:white;">1/82</td><td style="text-align:center;background:#58FA58;border-color:white;">1/23</td><td style="text-align:center;background:#58FA58;border-color:white;">1/57</td><td style="text-align:center;background:#58FA58;border-color:white;">1/47</td><td style="text-align:center;background:#58FA58;border-color:white;">2/122</td><td style="text-align:center;background:#58FA58;border-color:white;">1/49</td><td style="text-align:center;background:#58FA58;border-color:white;">1/134</td><td style="text-align:center;background:#58FA58;border-color:white;">1/154</td><td style="text-align:center;background:#58FA58;border-color:white;">3/187</td>
</tr>
<tr>
<td>3</td><td>Deep Run HS: Fantastic 100</td><td>11</td><td>553</td><td style="text-align:center;background:#58FA58;border-color:white;">1/2</td><td style="text-align:center;background:#58FA58;border-color:white;">1/4</td><td style="text-align:center;background:#58FA58;border-color:white;">1/13</td><td style="text-align:center;background:#58FA58;border-color:white;">1/19</td><td style="text-align:center;background:#58FA58;border-color:white;">1/29</td><td style="text-align:center;background:#58FA58;border-color:white;">1/53</td><td style="text-align:center;background:#58FA58;border-color:white;">1/69</td><td style="text-align:center;background:#58FA58;border-color:white;">1/65</td><td style="text-align:center;background:#58FA58;border-color:white;">1/58</td><td style="text-align:center;background:#58FA58;border-color:white;">1/135</td><td style="text-align:center;background:#58FA58;border-color:white;">1/106</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>4</td><td>Deep Run HS: HTCPCP://</td><td>11</td><td>703</td><td style="text-align:center;background:#58FA58;border-color:white;">1/1</td><td style="text-align:center;background:#58FA58;border-color:white;">1/3</td><td style="text-align:center;background:#58FA58;border-color:white;">1/25</td><td style="text-align:center;background:#58FA58;border-color:white;">1/19</td><td style="text-align:center;background:#58FA58;border-color:white;">2/112</td><td style="text-align:center;background:#58FA58;border-color:white;">1/36</td><td style="text-align:center;background:#58FA58;border-color:white;">1/48</td><td style="text-align:center;background:#58FA58;border-color:white;">2/118</td><td style="text-align:center;background:#58FA58;border-color:white;">1/30</td><td style="text-align:center;background:#58FA58;border-color:white;">1/92</td><td style="text-align:center;background:#58FA58;border-color:white;">1/179</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td>
</tr>
<tr>
<td>5</td><td>Loudoun Valley HS: Int Elligence</td><td>11</td><td>915</td><td style="text-align:center;background:#58FA58;border-color:white;">1/4</td><td style="text-align:center;background:#58FA58;border-color:white;">1/7</td><td style="text-align:center;background:#58FA58;border-color:white;">2/82</td><td style="text-align:center;background:#58FA58;border-color:white;">1/32</td><td style="text-align:center;background:#58FA58;border-color:white;">2/99</td><td style="text-align:center;background:#58FA58;border-color:white;">1/51</td><td style="text-align:center;background:#58FA58;border-color:white;">2/115</td><td style="text-align:center;background:#58FA58;border-color:white;">1/70</td><td style="text-align:center;background:#58FA58;border-color:white;">2/101</td><td style="text-align:center;background:#FF6666; border-color:white;">6/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/79</td><td style="text-align:center;background:#58FA58;border-color:white;">3/155</td>
</tr>
<tr>
<td>6</td><td>Lake Braddock SS: Harambe</td><td>10</td><td>601</td><td style="text-align:center;background:#58FA58;border-color:white;">1/9</td><td style="text-align:center;background:#58FA58;border-color:white;">1/11</td><td style="text-align:center;background:#58FA58;border-color:white;">1/21</td><td style="text-align:center;background:#58FA58;border-color:white;">2/142</td><td style="text-align:center;background:#58FA58;border-color:white;">1/89</td><td style="text-align:center;background:#58FA58;border-color:white;">1/46</td><td style="text-align:center;background:#58FA58;border-color:white;">1/61</td><td style="text-align:center;background:#58FA58;border-color:white;">1/39</td><td style="text-align:center;background:#58FA58;border-color:white;">1/24</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/139</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>7</td><td>Albemarle HS: Cyborg Wombats</td><td>10</td><td>660</td><td style="text-align:center;background:#58FA58;border-color:white;">1/4</td><td style="text-align:center;background:#58FA58;border-color:white;">1/9</td><td style="text-align:center;background:#58FA58;border-color:white;">1/14</td><td style="text-align:center;background:#58FA58;border-color:white;">1/162</td><td style="text-align:center;background:#58FA58;border-color:white;">1/63</td><td style="text-align:center;background:#58FA58;border-color:white;">2/115</td><td style="text-align:center;background:#58FA58;border-color:white;">1/46</td><td style="text-align:center;background:#58FA58;border-color:white;">1/83</td><td style="text-align:center;background:#58FA58;border-color:white;">1/48</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/96</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>8</td><td>TJ High School: TJHSST Frosh Team</td><td>10</td><td>747</td><td style="text-align:center;background:#58FA58;border-color:white;">1/6</td><td style="text-align:center;background:#58FA58;border-color:white;">1/9</td><td style="text-align:center;background:#58FA58;border-color:white;">1/50</td><td style="text-align:center;background:#58FA58;border-color:white;">1/40</td><td style="text-align:center;background:#58FA58;border-color:white;">1/68</td><td style="text-align:center;background:#58FA58;border-color:white;">1/77</td><td style="text-align:center;background:#58FA58;border-color:white;">1/93</td><td style="text-align:center;background:#58FA58;border-color:white;">2/139</td><td style="text-align:center;background:#58FA58;border-color:white;">1/116</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/129</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>9</td><td>Rock Ridge: Difference Engine</td><td>10</td><td>835</td><td style="text-align:center;background:#58FA58;border-color:white;">1/7</td><td style="text-align:center;background:#58FA58;border-color:white;">1/10</td><td style="text-align:center;background:#58FA58;border-color:white;">1/20</td><td style="text-align:center;background:#58FA58;border-color:white;">2/161</td><td style="text-align:center;background:#58FA58;border-color:white;">2/156</td><td style="text-align:center;background:#58FA58;border-color:white;">1/69</td><td style="text-align:center;background:#58FA58;border-color:white;">2/109</td><td style="text-align:center;background:#58FA58;border-color:white;">1/83</td><td style="text-align:center;background:#58FA58;border-color:white;">1/46</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/114</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>10</td><td>TJ High School: TJHSST Intermediate Team</td><td>10</td><td>933</td><td style="text-align:center;background:#58FA58;border-color:white;">1/3</td><td style="text-align:center;background:#58FA58;border-color:white;">1/8</td><td style="text-align:center;background:#58FA58;border-color:white;">1/21</td><td style="text-align:center;background:#58FA58;border-color:white;">1/38</td><td style="text-align:center;background:#58FA58;border-color:white;">2/109</td><td style="text-align:center;background:#58FA58;border-color:white;">4/207</td><td style="text-align:center;background:#58FA58;border-color:white;">2/126</td><td style="text-align:center;background:#FF6666; border-color:white;">4/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/66</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/70</td><td style="text-align:center;background:#58FA58;border-color:white;">1/185</td>
</tr>
<tr>
<td>11</td><td>Robinson Home: Wired Up</td><td>10</td><td>1016</td><td style="text-align:center;background:#58FA58;border-color:white;">1/5</td><td style="text-align:center;background:#58FA58;border-color:white;">1/7</td><td style="text-align:center;background:#58FA58;border-color:white;">2/82</td><td style="text-align:center;background:#58FA58;border-color:white;">1/78</td><td style="text-align:center;background:#58FA58;border-color:white;">2/125</td><td style="text-align:center;background:#58FA58;border-color:white;">2/111</td><td style="text-align:center;background:#58FA58;border-color:white;">1/129</td><td style="text-align:center;background:#58FA58;border-color:white;">3/220</td><td style="text-align:center;background:#58FA58;border-color:white;">2/99</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/40</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>12</td><td>Forest Park HS: Forest Park Brewins Team </td><td>9</td><td>732</td><td style="text-align:center;background:#58FA58;border-color:white;">1/10</td><td style="text-align:center;background:#58FA58;border-color:white;">1/23</td><td style="text-align:center;background:#58FA58;border-color:white;">1/17</td><td style="text-align:center;background:#58FA58;border-color:white;">1/152</td><td style="text-align:center;background:#58FA58;border-color:white;">1/93</td><td style="text-align:center;background:#58FA58;border-color:white;">1/72</td><td style="text-align:center;background:#58FA58;border-color:white;">1/61</td><td style="text-align:center;background:#58FA58;border-color:white;">2/162</td><td style="text-align:center;background:#58FA58;border-color:white;">1/122</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>13</td><td>Stone Bridge HS: Socrates Johnson</td><td>9</td><td>866</td><td style="text-align:center;background:#58FA58;border-color:white;">1/6</td><td style="text-align:center;background:#58FA58;border-color:white;">1/10</td><td style="text-align:center;background:#58FA58;border-color:white;">1/21</td><td style="text-align:center;background:#58FA58;border-color:white;">1/42</td><td style="text-align:center;background:#58FA58;border-color:white;">2/218</td><td style="text-align:center;background:#58FA58;border-color:white;">1/85</td><td style="text-align:center;background:#58FA58;border-color:white;">1/107</td><td style="text-align:center;background:#58FA58;border-color:white;">2/154</td><td style="text-align:center;background:#58FA58;border-color:white;">2/163</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>14</td><td>GSST: GSST - Seniors</td><td>9</td><td>1122</td><td style="text-align:center;background:#58FA58;border-color:white;">1/5</td><td style="text-align:center;background:#58FA58;border-color:white;">1/9</td><td style="text-align:center;background:#58FA58;border-color:white;">1/22</td><td style="text-align:center;background:#58FA58;border-color:white;">2/121</td><td style="text-align:center;background:#58FA58;border-color:white;">2/205</td><td style="text-align:center;background:#58FA58;border-color:white;">1/64</td><td style="text-align:center;background:#58FA58;border-color:white;">1/206</td><td style="text-align:center;background:#58FA58;border-color:white;">4/209</td><td style="text-align:center;background:#58FA58;border-color:white;">3/141</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>15</td><td>South Lakes HS: SLHS Team 1</td><td>8</td><td>761</td><td style="text-align:center;background:#58FA58;border-color:white;">1/4</td><td style="text-align:center;background:#58FA58;border-color:white;">1/12</td><td style="text-align:center;background:#58FA58;border-color:white;">1/30</td><td style="text-align:center;background:#58FA58;border-color:white;">1/57</td><td style="text-align:center;background:#58FA58;border-color:white;">1/184</td><td style="text-align:center;background:#58FA58;border-color:white;">2/223</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/152</td><td style="text-align:center;background:#58FA58;border-color:white;">1/79</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>16</td><td>Rock Ridge: I/O Error</td><td>8</td><td>944</td><td style="text-align:center;background:#58FA58;border-color:white;">2/58</td><td style="text-align:center;background:#58FA58;border-color:white;">1/17</td><td style="text-align:center;background:#58FA58;border-color:white;">1/89</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">3/179</td><td style="text-align:center;background:#58FA58;border-color:white;">1/112</td><td style="text-align:center;background:#58FA58;border-color:white;">1/126</td><td style="text-align:center;background:#58FA58;border-color:white;">1/155</td><td style="text-align:center;background:#58FA58;border-color:white;">1/148</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>17</td><td>Heritage HS: Math.pow(rishi,2);</td><td>8</td><td>1014</td><td style="text-align:center;background:#58FA58;border-color:white;">1/11</td><td style="text-align:center;background:#58FA58;border-color:white;">1/17</td><td style="text-align:center;background:#58FA58;border-color:white;">1/33</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/171</td><td style="text-align:center;background:#58FA58;border-color:white;">2/129</td><td style="text-align:center;background:#58FA58;border-color:white;">2/152</td><td style="text-align:center;background:#58FA58;border-color:white;">2/211</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/230</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>18</td><td>RMHS: RMHS 2</td><td>8</td><td>1044</td><td style="text-align:center;background:#58FA58;border-color:white;">2/70</td><td style="text-align:center;background:#58FA58;border-color:white;">1/10</td><td style="text-align:center;background:#58FA58;border-color:white;">2/102</td><td style="text-align:center;background:#58FA58;border-color:white;">1/67</td><td style="text-align:center;background:#58FA58;border-color:white;">1/161</td><td style="text-align:center;background:#58FA58;border-color:white;">1/151</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/230</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/213</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>19</td><td>GSST: GSST - The Beautiful Minds</td><td>7</td><td>576</td><td style="text-align:center;background:#58FA58;border-color:white;">1/4</td><td style="text-align:center;background:#58FA58;border-color:white;">1/8</td><td style="text-align:center;background:#58FA58;border-color:white;">1/59</td><td style="text-align:center;background:#58FA58;border-color:white;">1/47</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;background:#58FA58;border-color:white;">3/167</td><td style="text-align:center;background:#58FA58;border-color:white;">1/194</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/57</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>20</td><td>South Lakes HS: SLHS Team 2</td><td>7</td><td>650</td><td style="text-align:center;background:#58FA58;border-color:white;">1/4</td><td style="text-align:center;background:#58FA58;border-color:white;">1/7</td><td style="text-align:center;background:#58FA58;border-color:white;">2/135</td><td style="text-align:center;background:#58FA58;border-color:white;">1/56</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/156</td><td style="text-align:center;background:#58FA58;border-color:white;">1/109</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/163</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>21</td><td>Woodson High School: Javaliers 3</td><td>7</td><td>1042</td><td style="text-align:center;background:#58FA58;border-color:white;">1/7</td><td style="text-align:center;background:#58FA58;border-color:white;">1/12</td><td style="text-align:center;background:#58FA58;border-color:white;">2/85</td><td style="text-align:center;background:#58FA58;border-color:white;">1/175</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/230</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/213</td><td style="text-align:center;background:#58FA58;border-color:white;">4/220</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>22</td><td>GSST: GSST - The Third Graders!</td><td>6</td><td>351</td><td style="text-align:center;background:#58FA58;border-color:white;">1/6</td><td style="text-align:center;background:#58FA58;border-color:white;">1/11</td><td style="text-align:center;background:#58FA58;border-color:white;">1/32</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/76</td><td style="text-align:center;background:#58FA58;border-color:white;">2/148</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/58</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>23</td><td>Loudoun Valley HS: Coders R Us</td><td>6</td><td>394</td><td style="text-align:center;background:#58FA58;border-color:white;">1/6</td><td style="text-align:center;background:#58FA58;border-color:white;">1/11</td><td style="text-align:center;background:#58FA58;border-color:white;">1/24</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/68</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/133</td><td style="text-align:center;background:#58FA58;border-color:white;">2/132</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>24</td><td>Deep Run HS: team_name</td><td>6</td><td>518</td><td style="text-align:center;background:#58FA58;border-color:white;">1/8</td><td style="text-align:center;background:#58FA58;border-color:white;">1/14</td><td style="text-align:center;background:#58FA58;border-color:white;">1/45</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/191</td><td style="text-align:center;background:#58FA58;border-color:white;">2/209</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/31</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>25</td><td>Heritage HS: Lexical Poorgrammars</td><td>6</td><td>537</td><td style="text-align:center;background:#58FA58;border-color:white;">1/8</td><td style="text-align:center;background:#58FA58;border-color:white;">1/17</td><td style="text-align:center;background:#58FA58;border-color:white;">1/74</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/188</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/107</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/143</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>26</td><td>NCS: Raiders1</td><td>6</td><td>556</td><td style="text-align:center;background:#58FA58;border-color:white;">1/6</td><td style="text-align:center;background:#58FA58;border-color:white;">1/27</td><td style="text-align:center;background:#58FA58;border-color:white;">1/58</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/222</td><td style="text-align:center;background:#58FA58;border-color:white;">1/137</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/86</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>27</td><td>Loudoun Valley HS: Java Whisperers</td><td>6</td><td>592</td><td style="text-align:center;background:#58FA58;border-color:white;">1/16</td><td style="text-align:center;background:#58FA58;border-color:white;">1/12</td><td style="text-align:center;background:#58FA58;border-color:white;">3/214</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/55</td><td style="text-align:center;background:#58FA58;border-color:white;">1/187</td><td style="text-align:center;background:#FF6666; border-color:white;">4/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/68</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>28</td><td>Broad Run High School: Broad Run Team 1</td><td>6</td><td>608</td><td style="text-align:center;background:#58FA58;border-color:white;">1/4</td><td style="text-align:center;background:#58FA58;border-color:white;">1/7</td><td style="text-align:center;background:#58FA58;border-color:white;">1/58</td><td style="text-align:center;background:#58FA58;border-color:white;">2/125</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/190</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/184</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>29</td><td>Park View HS: ParkView Team1</td><td>6</td><td>655</td><td style="text-align:center;background:#58FA58;border-color:white;">1/8</td><td style="text-align:center;background:#58FA58;border-color:white;">1/23</td><td style="text-align:center;background:#58FA58;border-color:white;">1/44</td><td style="text-align:center;background:#58FA58;border-color:white;">2/180</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/219</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/161</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>30</td><td>Rock Ridge: No Bears in Schools</td><td>6</td><td>685</td><td style="text-align:center;background:#58FA58;border-color:white;">2/66</td><td style="text-align:center;background:#58FA58;border-color:white;">1/11</td><td style="text-align:center;background:#58FA58;border-color:white;">1/31</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/220</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/218</td><td style="text-align:center;background:#58FA58;border-color:white;">1/119</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>31</td><td>Albemarle HS: Two and a Half Men</td><td>6</td><td>790</td><td style="text-align:center;background:#58FA58;border-color:white;">1/26</td><td style="text-align:center;background:#58FA58;border-color:white;">2/110</td><td style="text-align:center;background:#58FA58;border-color:white;">1/55</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/177</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/228</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/154</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>32</td><td>Lake Braddock SS: Coderz</td><td>5</td><td>448</td><td style="text-align:center;background:#58FA58;border-color:white;">1/4</td><td style="text-align:center;background:#58FA58;border-color:white;">1/9</td><td style="text-align:center;background:#58FA58;border-color:white;">2/136</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/111</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">3/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/148</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>33</td><td>Powhatan HS: int elliGents</td><td>5</td><td>477</td><td style="text-align:center;background:#58FA58;border-color:white;">1/9</td><td style="text-align:center;background:#58FA58;border-color:white;">1/14</td><td style="text-align:center;background:#58FA58;border-color:white;">1/39</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">4/162</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/193</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">4/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>34</td><td>Dominion HS: Titans 1</td><td>5</td><td>576</td><td style="text-align:center;background:#58FA58;border-color:white;">1/12</td><td style="text-align:center;background:#58FA58;border-color:white;">1/17</td><td style="text-align:center;background:#58FA58;border-color:white;">1/32</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/229</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">3/226</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>35</td><td>Albemarle HS: Lucid Cash and the Compli</td><td>5</td><td>586</td><td style="text-align:center;background:#58FA58;border-color:white;">1/35</td><td style="text-align:center;background:#58FA58;border-color:white;">1/43</td><td style="text-align:center;background:#58FA58;border-color:white;">1/98</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">3/237</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/133</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>36</td><td>Powhatan HS: MightyMorphin PowArraynge</td><td>5</td><td>675</td><td style="text-align:center;background:#58FA58;border-color:white;">2/72</td><td style="text-align:center;background:#58FA58;border-color:white;">1/13</td><td style="text-align:center;background:#58FA58;border-color:white;">2/132</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/201</td><td style="text-align:center;background:#58FA58;border-color:white;">1/217</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>37</td><td>Stone Bridge HS: Herman the Kid</td><td>4</td><td>223</td><td style="text-align:center;background:#58FA58;border-color:white;">1/8</td><td style="text-align:center;background:#58FA58;border-color:white;">1/17</td><td style="text-align:center;background:#58FA58;border-color:white;">1/50</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/148</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>38</td><td>Stone Bridge HS: Maxine of Arc</td><td>4</td><td>268</td><td style="text-align:center;background:#58FA58;border-color:white;">1/3</td><td style="text-align:center;background:#58FA58;border-color:white;">1/7</td><td style="text-align:center;background:#58FA58;border-color:white;">2/91</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/127</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>39</td><td>Heritage HS: NullPointerExceptions</td><td>4</td><td>315</td><td style="text-align:center;background:#58FA58;border-color:white;">1/5</td><td style="text-align:center;background:#58FA58;border-color:white;">1/20</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/138</td><td style="text-align:center;background:#58FA58;border-color:white;">1/132</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>40</td><td>Woodson High School: Genetic Algorithms</td><td>4</td><td>347</td><td style="text-align:center;background:#58FA58;border-color:white;">1/5</td><td style="text-align:center;background:#58FA58;border-color:white;">1/10</td><td style="text-align:center;background:#58FA58;border-color:white;">1/154</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">9/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;background:#58FA58;border-color:white;">3/138</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>41</td><td>Dominion HS: Titans2</td><td>4</td><td>412</td><td style="text-align:center;background:#58FA58;border-color:white;">1/8</td><td style="text-align:center;background:#58FA58;border-color:white;">1/11</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/189</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">3/164</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>42</td><td>NCS: Raiders2</td><td>4</td><td>494</td><td style="text-align:center;background:#58FA58;border-color:white;">1/27</td><td style="text-align:center;background:#58FA58;border-color:white;">1/27</td><td style="text-align:center;background:#58FA58;border-color:white;">5/202</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/138</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>43</td><td>Galileo HS: Galileo Magnet High Schoo</td><td>3</td><td>95</td><td style="text-align:center;background:#58FA58;border-color:white;">1/4</td><td style="text-align:center;background:#58FA58;border-color:white;">1/10</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">1/81</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>44</td><td>Woodson High School: Javaliers 2</td><td>3</td><td>295</td><td style="text-align:center;background:#58FA58;border-color:white;">1/7</td><td style="text-align:center;background:#58FA58;border-color:white;">1/45</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;background:#58FA58;border-color:white;">2/223</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>45</td><td>Powhatan HS: Bears Beets Battlestar Ga</td><td>2</td><td>132</td><td style="text-align:center;background:#58FA58;border-color:white;">1/16</td><td style="text-align:center;background:#58FA58;border-color:white;">1/116</td><td style="text-align:center;background:#FF6666; border-color:white;">1/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
<tr>
<td>46</td><td>Broad Run High School: Broad Run Team 2</td><td>1</td><td>5</td><td style="text-align:center;background:#58FA58;border-color:white;">1/5</td><td style="text-align:center;background:#FF6666; border-color:white;">2/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td><td style="text-align:center;border-color:white;">0/--</td>
</tr>
</tbody>
</table>
</body>
</html>
